# Generated by Django 2.0.6 on 2018-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WD', '0002_auto_20180613_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
