# Generated by Django 2.0.6 on 2018-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WD', '0004_auto_20180616_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
